### ISSUE TITLE
UI issue with checkbox

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-getting-started-android#10]
In the task list page, when updating two or more tasks swiftly one after the other, the UI doesn't work as expected. tested on live network. i.e., if you try to check more than one checkbox one after the other immediately, only first task is checked. second one is unchecked but the status is updated as completed which is not correct.

But if you navigate to other page and return, the UI state is correct.

**Comment by S-Coyle** [comment]
@safesurfer is this good to be placed in Done as it was tested on PR #17 ?

**Comment by safesurfer** [comment]
Yes, moving it to Done
